Config                         = {}

Config.useQalleCameraSystem    = false       --( https://github.com/qalle-fivem/esx-qalle-camerasystem )
Config.chancePoliceNoti        = 50          -- the percent police get notified (only numbers like 30, 10, 40. You get it.)
Config.useBlip                 = true      -- if u want blip
Config.useInteractSound        = false       -- if you wanna use InteractSound (when u lockpick the door)
Config.cooldownTime            = 10        -- cooldown Time in minutes

Config.CheckTime               = true
--Config.StartHour               = 0 -- 0 to 24 h
--Config.EndHour                 = 23

Config.sellPoint = {x = 412.31, y = 314.11, z = 103.02, sprite = 267, color = 56, name = 'Pawn Shop'}

Config.burglaryPlaces = {
    -- ["Tinsel Towers Apt 42"] = {
    --     pos = { x = -619.28, y = 37.95, z = 43.6, h = 357.03},  -- door coords
    --     locked = true,
    --     cooldown = 0,
    --     inside = { x = -610.48 , y = 58.95 , z = 98.2, h = 81.56 },  -- Inside coords
    --     animPos = { x = -619.28, y = 37.95, z = 43.6, h = 357.03 },   -- The animation position
    -- },

    ["apartment1-hillcrest-ave"] = {
        pos = { x = -686.12, y = 596.39, z = 143.64, h = 218.12},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = -682.47, y = 592.81, z = 145.39, h = 81.56},  -- Inside coords
        animPos = { x = -685.64, y = 596.43, z = 143.50, h = 222.52},   -- The animation position
    },
	
	["apartment2-hillcrest-ave"] = {
        pos = { x = -753.46, y = 620.40, z = 142.85, h = 104.48},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = -758.27, y = 619.08, z = 144.15, h = 106.67},  -- Inside coords
        animPos = { x = -753.46, y = 620.40, z = 142.85, h = 104.48},   -- The animation position
    },
	
	["apartment3-hillcrest-ave"] = {
        pos = { x = -852.98, y = 695.38, z = 148.79, h = 181.07},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = -860.09, y = 691.44, z = 152.86, h = 182.15},  -- Inside coords
        animPos = { x = -852.54, y = 695.09, z = 148.99, h = 176.50},   -- The animation position
    },

	-- ["north-conker-ave"] = {
    --     pos = { x = 374.12, y = 427.75, z = 145.80, h = 181.07},  -- door coords
    --     locked = true,
    --     cooldown = 0,
    --     inside = { x = 373.68, y = 423.90, z = 145.91, h = 168.94},  -- Inside coords
    --     animPos = { x = 373.84, y = 427.37, z = 145.48, h = 256.50},   -- The animation position
    -- },
	
	-- ["nspt-de-base"] = {
    --     pos = { x = 291.31, y = -1078.61, z = 29.4, h = 91.78},  -- door coords
    --     locked = true,
    --     cooldown = 0,
    --     inside = { x = 265.97, y = -1007.39, z = -101.01, h = 355.99},  -- Inside coords
    --     animPos = { x = 291.78, y = -1078.61, z = 29.4, h = 91.55},   -- The animation position
    -- },
	
	-- ["integrity-way"] = {
    --     pos = { x = -46.96, y = -584.67, z = 37.95, h = 249.16},  -- door coords
    --     locked = true,
    --     cooldown = 0,
    --     inside = { x = -24.37, y = -597.68, z = 80.03, h = 237.79},  -- Inside coords
    --     animPos = { x = -46.96, y = -584.67, z = 37.95, h = 249.16},   -- The animation position
	-- },
	
	["Warehouse-small"] = {
        pos = { x = 661.65, y = -2643.95, z = 8.40, h = 0.42},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = 1087.53, y = -3099.096, z = -38.99, h = 265.61},  -- Inside coords
        animPos = { x = 661.65, y = -2643.95, z = 8.40, h = 0.42},   -- The animation position
    },
}

Config.burglaryInside = {
    -- --Tinsel Towers Apt 42--- $2450ish max (very unlikely) 1/24 chance per search
	-- ["draw1"] = { house = "Tinsel Towers Apt 42", x = -601.45, y = 45.85, z = 97.40, items = {'omega','rolex','laptop','junk','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["draw2"] = { house = "Tinsel Towers Apt 42", x = -601.45, y = 43.62, z = 97.40, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["speaker1"] = { house = "Tinsel Towers Apt 42", x = -604.26, y = 40.90, z = 97.40, items = {'speaker', '', 'speaker','',''}, names = {'Speaker', 'Junk', 'Speaker','Junk'}, maxamount = 1, amount = math.random(1,2)},
	-- ["speaker2"] = { house = "Tinsel Towers Apt 42", x = -608.47, y = 40.79, z = 97.40, items = {'speaker', '', 'speaker','',''}, names = {'Speaker', 'Junk', 'Speaker','Junk'}, maxamount = 1, amount = math.random(1,2)},
	-- --bedroom
	-- ["draw3"] = { house = "Tinsel Towers Apt 42", x = -598.58, y = 49.69, z = 97.03, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["draw4"] = { house = "Tinsel Towers Apt 42", x = -598.58, y = 47.81, z = 97.11, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["draw5"] = { house = "Tinsel Towers Apt 42", x = -593.20, y = 50.45, z = 96.50, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	-- ["draw6"] = { house = "Tinsel Towers Apt 42", x = -597.42, y = 52.15, z = 97.00, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["draw7"] = { house = "Tinsel Towers Apt 42", x = -593.20, y = 47.00, z = 96.50, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	-- ["wardrobe1"] = { house = "Tinsel Towers Apt 42", x = -595.95, y = 56.13, z = 97.0, items = {'','ring','','omega',''}, names = {'Junk', 'Gold Ring','Junk','Omega Watch','Junk'}, maxamount = 1, amount = math.random(1,1)},
	-- ["wardrobe2"] = { house = "Tinsel Towers Apt 42", x = -593.22, y = 56.13, z = 97.0, items = {'','ring','','oldcoin',''}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk'}, maxamount = 1, amount = math.random(1,1)},
	-- --office
	-- ["laptoptable1"] = { house = "Tinsel Towers Apt 42", x = -625.50, y = 50.14, z = 97.50, items = {'laptop','','gamingperipherals'}, names = {'Laptop','Junk','Headphones'}, maxamount = 1, amount = math.random(1,1)},
	-- --bathroom
	-- ["sinkl"] = { house = "Tinsel Towers Apt 42", x = -589.89, y = 52.70, z = 97.00, items = {'','dildo','','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, maxamount = 1, amount = math.random(1,1)},
	-- ["sink2"] = { house = "Tinsel Towers Apt 42", x = -590.03, y = 50.05, z = 96.50, items = {'','dildo','','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, maxamount = 1, amount = math.random(1,1)},
	 
	 
	--apt-hill-crest1 ---- $2050ish max (very unlikely) 1/24 chance per search
	["draw8"] = { house = "apartment1-hillcrest-ave", x = -672.68, y = 581.6, z = 144.97, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["draw9"] = { house = "apartment1-hillcrest-ave", x = -674.76, y = 584.88, z = 145.00, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["skybox1"] = { house = "apartment1-hillcrest-ave", x = -664.40, y = 585.27, z = 144.30, items = {'console','console','',''}, names = {'PS4','Xbox 1','Junk','Junk'}, maxamount = 1, amount = math.random(1,1)},
	 --kitchen
	["draw10"] = { house = "apartment1-hillcrest-ave", x = -675.73, y = 595.65, z = 145.38, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	["draw11"] = { house = "apartment1-hillcrest-ave", x = -674.09, y = 593.43, z = 145.38, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["draw12"] = { house = "apartment1-hillcrest-ave", x = -673.00, y = 595.06, z = 145.38, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	--bedroom
	["speaker3"] = { house = "apartment1-hillcrest-ave", x = -672.00, y = 581.21, z = 141.57, items = {'speaker', '', 'speaker','','ifruit'}, names = {'Speaker','Junk','Speaker','Junk','ifruit'}, maxamount = 1, amount = math.random(1,1)},
	["draw13"] = { house = "apartment1-hillcrest-ave", x = -664.45, y = 584.89, z = 141.40, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["wardrobe3"] = { house = "apartment1-hillcrest-ave", x = -672.00, y = 587.6, z = 141.57, items = {'','ring','','oldcoin','','rolex'}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk','Rolex Watch'}, maxamount = 1, amount = math.random(1,1)},
	--bathroom
	["18ct Diamond Ring"] = { house = "apartment1-hillcrest-ave", x = -674.27, y = 595.29, z = 141.50, items = {'','dildo','','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, maxamount = 1, amount = math.random(1,1)},
	["Hairspray"] = { house = "apartment1-hillcrest-ave", x = -673.40, y = 595.80, z = 141.50, items = {'','dildo','','ring'}, names = {'Strap On','Dildo','Book','Gold Ring'}, maxamount = 1, amount = math.random(1,1)},
	--downstairs
	["shelve1"] = { house = "apartment1-hillcrest-ave", x = -682.05, y = 596.33, z = 137.88, items = {'','ring','','oldcoin',''}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk'}, maxamount = 1, amount = math.random(1,1)},
	
	
	--apt-hill-crest2 ---- $2450ish max (very unlikely) 1/24 chance per search
	["draw14"] = { house = "apartment2-hillcrest-ave", x = -768.24, y = 615.00, z = 143.33, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	["draw15"] = { house = "apartment2-hillcrest-ave", x = -758.26, y = 611.59, z = 144.00, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["shelve2"] = { house = "apartment2-hillcrest-ave", x = -768.05, y = 608.07, z = 143.93, items = {'','ring','','passport',''}, names = {'Junk', 'Ring','Junk','Passport','Junk'}, maxamount = 1, amount = math.random(1,2)},
	["Treasure Map"] = { house = "apartment2-hillcrest-ave", x = -773.13, y = 613.82, z = 143.73, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifuit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["Sojo Beans"] = { house = "apartment2-hillcrest-ave", x = -759.46, y = 609.63, z = 144.14, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifuit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["draw16"] = { house = "apartment2-hillcrest-ave", x = -761.59, y = 613.22, z = 144.14, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifuit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	--bedroom
	["drawadded"] = { house = "apartment2-hillcrest-ave", x = -774.54, y = 613.14, z = 140.70, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	["drawadded2"] = { house = "apartment2-hillcrest-ave", x = -772.95, y = 613.60, z = 140.40, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	["drawadded3"] = { house = "apartment2-hillcrest-ave", x = -772.13, y = 605.28, z = 140.25, items = {'laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["drawadded4"] = { house = "apartment2-hillcrest-ave", x = -769.31, y = 606.24, z = 140.25, items = {'laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["sinkadded"] = { house = "apartment2-hillcrest-ave", x = -759.14, y = 610.45, z = 140.00, items = {'','dildo','','ring','oldcoin'}, names = {'Junk','Dildo','Book','Gold Ring','Old Coin'}, maxamount = 1, amount = math.random(1,2)},
	--downstairs
	["Book of Ree"] = { house = "apartment2-hillcrest-ave", x = -755.02, y = 617.38, z = 136.88, items = {'','ring','','oldcoin','',''}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk','Junk'}, maxamount = 1, amount = math.random(1,2)},
	["Cracked Ornament"] = { house = "apartment2-hillcrest-ave", x = -760.85, y = 619.01, z = 136.52, items = {'','rareornament','','oldcoin',''}, names = {'Junk', 'Rare Ornament','Junk','Old Coin','Junk'}, maxamount = 1, amount = math.random(1,1)},
	["laptoptable2"] = { house = "apartment2-hillcrest-ave", x = -763.41, y = 613.43, z = 136.53, items = {'laptop','','gamingperipherals',''}, names = {'Laptop','Junk','Mouse','Junk'}, maxamount = 1, amount = math.random(1,1)},
	["laptoptable3"] = { house = "apartment2-hillcrest-ave", x = -760.74, y = 614.33, z = 136.53, items = {'tablet','','',''}, names = {'ipad','Junk','Junk','Junk'}, maxamount = 1, amount = math.random(1,1)},
	
	
	--apt-hill-crest3 ---- $2450ish max (very unlikely) 1/24 chance per search
	["draw15"] = { house = "apartment3-hillcrest-ave", x = -859.50, y = 675.05, z = 152.45, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["draw18"] = { house = "apartment3-hillcrest-ave", x = -856.12, y = 686.08, z = 152.88, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["draw17"] = { house = "apartment3-hillcrest-ave", x = -852.16, y = 687.18, z = 152.88, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	["drawadded6"] = { house = "apartment3-hillcrest-ave", x = -853.79, y = 688.90, z = 152.65, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["drawadded5"] = { house = "apartment3-hillcrest-ave", x = -859.72, y = 679.15, z = 152.65, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["skybox2"] = { house = "apartment3-hillcrest-ave", x = -851.18, y = 674.83, z = 152.45, items = {'console','console','',''}, names = {'PS4','Xbox 1','Junk','Junk'}, maxamount = 1, amount = math.random(1,1)},
	--downstairs
	["Panther Ornament"] = { house = "apartment3-hillcrest-ave", x = -860.95, y = 693.26, z = 149.45, items = {'rareornament','','','oldcoin'}, names = {'rareornament','','','Old Coin'}, maxamount = 1, amount = math.random(1,1)},
	["Breath Fresh"] = { house = "apartment3-hillcrest-ave", x = -853.52, y = 687.72, z = 149.07, items = {'','diamond','','ring','diamondring'}, names = {'Strap On','Diamond','Book','Gold Ring','Diamond Ring'}, maxamount = 1, amount = math.random(1,1)},
	["9ct Ring"] = { house = "apartment3-hillcrest-ave", x = -852.08, y = 687.72, z = 149.07, items = {'','dildo','','ring','diamondring'}, names = {'Strap On','Dildo','Book','Gold Ring','Diamond Ring'}, maxamount = 1, amount = math.random(1,1)},
	["shelve3"] = { house = "apartment3-hillcrest-ave", x = -854.72, y = 680.32, z = 149.05, items = {'','ring','','omega','','rolex',''}, names = {'Junk', 'Gold Ring','Junk','Omega Watch','Junk','Rolex Watch','Junk'}, maxamount = 1, amount = math.random(1,1)},
	["Pot Ornament"] = { house = "apartment3-hillcrest-ave", x = -859.2, y = 695.81, z = 145.24, items = {'','rareornament','','oldcoin',''}, names = {'Junk', 'Rare Ornament','Junk','Old Coin','Junk'}, maxamount = 1, amount = math.random(1,1)},
	["draw19"] = { house = "apartment3-hillcrest-ave", x = -856.1, y = 699.15, z = 145.25, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	["wardrobe4"] = { house = "apartment3-hillcrest-ave", x = -859.53, y = 675.24, z = 148.85, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	["Broken Watch"] = { house = "apartment3-hillcrest-ave", x = -851.13, y = 677.22, z = 148.85, items = {'','dildo','','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, maxamount = 1, amount = math.random(1,1)},
	
	-- --corkers-ave -  (near pawnshop)--- $1600ish max (very unlikely) 1/24 chance per search
	-- ["draw20"] = { house = "north-conker-ave", x = 368.80, y = 408.21, z = 145.5, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["draw21"] = { house = "north-conker-ave", x = 368.80, y = 407.68, z = 145.5, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["Book of Memes"] = { house = "north-conker-ave", x = 373.31 , y = 426.03, z = 143.10, items = {'','dildo','','ring','goldbracelet'}, names = {'Junk','Dildo','Book','Gold Ring','Gold Bracelet'}, maxamount = 1, amount = math.random(1,1)},
	-- ["Bowl"] = { house = "north-conker-ave", x = 377.75, y = 419.67, z = 145.9, items = {'','ring','','oldcoin',''}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk'}, maxamount = 1, amount = math.random(1,1)},
	-- --downstairs
	-- ["SteelSeries Headphones"] = { house = "north-conker-ave", x = 373.35, y = 433.39, z = 138.30, items = {'laptop','','gamingperipherals',''}, names = {'Laptop','Junk','Keyboard','Junk'}, maxamount = 1, amount = math.random(1,1)},
	-- --bedroom
	-- ["Pink Thing"] = { house = "north-conker-ave", x = 376.69, y = 404.06, z = 141.75, items = {'','dildo','','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, maxamount = 1, amount = math.random(1,1)},
	-- ["Amber Leaf"] = { house = "north-conker-ave", x = 373.62, y = 412.50, z = 142.10, items = {'','','lotteryticket'}, names = {'','Junk','Lottery Ticket'}, maxamount = 1, amount = math.random(1,2)},
	-- ["Lotto2"] = { house = "north-conker-ave", x = 368.61, y = 406.54, z = 142.10, items = {'wallet','pickledanimal',''}, names = {'Wallet','Zevas Jar of Pickled Animals',''}, maxamount = 1, amount = math.random(1,1)},
	-- ["Zevas"] = { house = "north-conker-ave", x = 369.11, y = 403.36, z = 141.50, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["Diamond"] = { house = "north-conker-ave", x = 377.57, y = 419.12, z = 141.40, items = {'diamond','',''}, names = {'Diamond','',''}, maxamount = 1, amount = math.random(1,1)},
	-- ["added"] = { house = "north-conker-ave", x = 379.36, y = 429.82, z = 138.3, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	
	
	
	-- --apt-de-base(nesr PD) -- high risk, higher reward $2450ish max (very unlikely) 1/24 chance per search
	-- --bed
	-- ["Rolex"] = { house = "nspt-de-base", x = 262.95, y = -1004.51, z = -98.90, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- --main room
	-- ["Leather Wallet"] = { house = "nspt-de-base", x = 266.10, y = -999.4, z = -99.01, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["Fake Passport"] = { house = "nspt-de-base", x = 260.19, y = -997.11, z = -97.30, items = {'omega','rolex','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["Mouldy Spoon"] = { house = "nspt-de-base", x = 266.11, y = -996.59, z = -99.01, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["18ct Ring"] = { house = "nspt-de-base", x = 256.90, y = -1001.49, z = -99.01, items = {'omega','rolex','laptop','','','pickledanimal','santash''#at','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	-- ["FHM"] = { house = "nspt-de-base", x = 260.80, y = -994.87, z = -99.50, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["Packet of RAWS"] = { house = "nspt-de-base", x = 262.53, y = -1000.27, z = -99.30, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
	-- ["Picture Frame"] = { house = "nspt-de-base", x = 256.25, y = -996.95, z = -98.41, items = {'','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
	-- ["Ripped Clothes"] = { house = "nspt-de-base", x = 260.68, y = -1004.6, z = -99.01, items = {'laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,1)},
	-- ["Xbox One"] = { house = "nspt-de-base", x = 263.03, y = -1002.47, z = -99.00, items = {'console','console','',''}, names = {'PS4','Xbox 1','Junk','Junk'}, maxamount = 1, amount = math.random(1,1)},


	----small warehouse
	["1"] = { house = "warehouse", x = 1104.54, y = -3102.39, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','bobbypin'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Bobbypin'}, maxamount = 3, amount = math.random(1,5)},
	["2"] = { house = "warehouse", x = 1103.83, y = -3102.39, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','bobbypin'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Bobbypin'}, maxamount = 3, amount = math.random(1,5)},
	["3"] = { house = "warehouse", x = 1103.00, y = -3102.41, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','bobbypin','pistolclip'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Bobbypin','Pistol Clip'}, maxamount = 3, amount = math.random(1,5)},
	["4"] = { house = "warehouse", x = 1102.04, y = -3102.25, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','bobbypin'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Bobbypin'}, maxamount = 3, amount = math.random(1,5)},
	["5"] = { house = "warehouse", x = 1100.99, y = -3102.25, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','bobbypin'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Bobbypin'}, maxamount = 3, amount = math.random(1,5)},
	["6"] = { house = "warehouse", x = 1100.00, y = -3102.25, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','bobbypin'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Bobbypin'}, maxamount = 3, amount = math.random(1,5)},
	["7"] = { house = "warehouse", x = 1103.77, y = -3097.75, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','bobbypin','pistolclip'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Bobbypin','Pistol Clip'}, maxamount = 3, amount = math.random(1,5)},
	["8"] = { house = "warehouse", x = 1101.34, y = -3097.80, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','semiautotrigger','bobbypin'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Semi Auto Trigger','Bobbypin'}, maxamount = 3, amount = math.random(1,5)},
	["9"] = { house = "warehouse", x = 1097.40, y = -3098.09, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','semiautotrigger','bobbypin'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Semi Auto Trigger','Bobbypin'}, maxamount = 3, amount = math.random(1,5)},
	["10"] = { house = "warehouse", x = 1095.08, y = -3098.03, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','semiautotrigger','bobbypin','autotrigger'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','','Pistol Body','Trigger','Metal pipe','Semi Auto Trigger','Bobby pin','Auto Trigger'}, maxamount = 3, amount = math.random(1,5)},
	["11"] = { house = "warehouse", x = 1091.39, y = -3098.24, z = -38.99, items = {'metal','metal','metal','cloth','cloth','cloth','spring','spring','spring','','','','','','','pistolbody','trigger','metalpipe','semiautobody','bobbypin'}, names = {'Metal','Metal','Metal','Cloth','Cloth','Spring','Spring','Spring','Cloth','Screwdriver','Nails','Bolts','Wrench','Rubber','Junk','Pistol Body','Trigger','Metal pipe','Semi Auto Body','Bobbypin'}, maxamount = 3, amount = math.random(1,5)},


	--desk
	["d1"] = { house = "warehouse", x = 1088.44, y = -3101.68, z = -38.99, items = {'bobbypin','rubberband','spring','','','pistolclip'}, names = {'Bobby Pin','Rubber Band','Spring','Junk','Junk','Pistol Clip'}, maxamount = 4, amount = math.random(1,5)},
}


-- 	--integirty-way - $2050ish max (very unlikely) 1/25 chance per search---
-- 	["speakeradded2"] = { house = "integrity-way", x = -604.26, y = 40.90, z = 97.40, items = {'speaker', '', 'speaker','',''}, names = {'Speaker', 'Junk', 'Speaker','Junk'}, maxamount = 1, amount = math.random(1,2)},
-- 	["speakeradded"] = { house = "integrity-way", x = -604.26, y = 40.90, z = 97.40, items = {'speaker', '', 'speaker','',''}, names = {'Speaker', 'Junk', 'Speaker','Junk'}, maxamount = 1, amount = math.random(1,2)},
-- 	--bedroom
-- 	["9c Ringg"] = { house = "integrity-way", x = -27.32, y = -580.18, z = 79.23, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,1)},
-- 	["Packet of Tissues"] = { house = "integrity-way", x = -11.81, y = -599.34, z = 79.43, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
-- 	["drawaddedx"] = { house = "integrity-way", x = -34.36, y = -586.70, z = 78.83, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
-- 	["drawaddedy"] = { house = "integrity-way", x = -37.31, y = -583.69, z = 78.50, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
-- 	["drawaddedp"] = { house = "integrity-way", x = -36.23, y = -580.71 , z = 78.50, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 2, amount = math.random(1,2)},
-- 	--printer
-- 	["Rolex Submariner"] = { house = "integrity-way", x = -9.34, y = -599.51, z = 79.43, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
-- 	--bathroom
-- 	["Showercap"] = { house = "integrity-way", x = -40.57, y = -582.22, z = 78.0, items = {'','dildo','','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, maxamount = 1, amount = math.random(1,1)},
-- 	["22ct Diamond Ring"] = { house = "integrity-way", x = -41.40, y = -584.80, z = 78.65, items = {'','dildo','','ring','diamondring'}, names = {'Junk','Dildo','Book','Gold Ring','diamondring'}, maxamount = 1, amount = math.random(1,1)},
-- 	["Remote"] = { house = "integrity-way", x = -31.76, y = -583.29, z = 78.87, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
-- 	["PS4"] = { house = "integrity-way", x = -22.69, y = -579.47, z = 78.80, items = {'console','console','',''}, names = {'PS4','Xbox 1','Junk','Junk'}, maxamount = 1, amount = math.random(1,1)},
-- 	["drawt"] = { house = "integrity-way", x = -10.50, y = -584.59, z = 79.6, items = {'omega','rolex','laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
-- 	["drawy"] = { house = "integrity-way", x = -13.01, y = -589.67, z = 79.43, items = {'laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
-- 	["Folder "] = { house = "integrity-way", x = -7.20, y = -594.15, z = 79.43, items = {'laptop','','','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, maxamount = 1, amount = math.random(1,1)},
-- }

Config.closets = {
    ["Robban's Closet"] = { house = "fuck-knows", x = 351.24, y = -993.53, z = -99.2, items = {'shirt', 'pants', 'hat', 'shoes'}, shirtAmount = math.random(1,3), pantsAmount = math.random(1,3), hatAmount = math.random(1,2), shoesAmount = math.random(1,2)},
}
