Config                         = {}

Config.useQalleCameraSystem    = false       --( https://github.com/qalle-fivem/esx-qalle-camerasystem )
Config.chancePoliceNoti        = 50          -- the percent police get notified (only numbers like 30, 10, 40. You get it.)
Config.useBlip                 = true      -- if u want blip
Config.useInteractSound        = false       -- if you wanna use InteractSound (when u lockpick the door)
Config.cooldownTime            = 10        -- cooldown Time in minutes

Config.CheckTime               = true
--Config.StartHour               = 0 -- 0 to 24 h
--Config.EndHour                 = 23

Config.sellPoint = {x = 412.31, y = 314.11, z = 103.02, sprite = 267, color = 56, name = 'Pawn Shop'}

Config.burglaryPlaces = {
    ["Tinsel Towers Apt 42"] = {
        pos = { x = -619.28, y = 37.95, z = 43.6, h = 357.03},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = -610.48 , y = 58.95 , z = 98.2, h = 81.56 },  -- Inside coords
        animPos = { x = -619.28, y = 37.95, z = 43.6, h = 357.03 },   -- The animation position
    },

    ["apartment1-hillcrest-ave"] = {
        pos = { x = -686.12, y = 596.39, z = 143.64, h = 218.12},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = -682.47, y = 592.81, z = 145.39, h = 81.56},  -- Inside coords
        animPos = { x = -685.64, y = 596.43, z = 143.50, h = 222.52},   -- The animation position
    },
	
	["apartment2-hillcrest-ave"] = {
        pos = { x = -753.46, y = 620.40, z = 142.85, h = 104.48},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = -758.27, y = 619.08, z = 144.15, h = 106.67},  -- Inside coords
        animPos = { x = -753.46, y = 620.40, z = 142.85, h = 104.48},   -- The animation position
    },
	
	["apartment3-hillcrest-ave"] = {
        pos = { x = -852.98, y = 695.38, z = 148.79, h = 181.07},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = -860.09, y = 691.44, z = 152.86, h = 182.15},  -- Inside coords
        animPos = { x = -852.54, y = 695.09, z = 148.99, h = 176.50},   -- The animation position
    },

	["north-conker-ave"] = {
        pos = { x = 374.12, y = 427.75, z = 145.80, h = 181.07},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = 373.68, y = 423.90, z = 145.91, h = 168.94},  -- Inside coords
        animPos = { x = 373.84, y = 427.37, z = 145.48, h = 256.50},   -- The animation position
    },
	
	["nspt-de-base"] = {
        pos = { x = 291.31, y = -1078.61, z = 29.4, h = 91.78},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = 265.97, y = -1007.39, z = -101.01, h = 355.99},  -- Inside coords
        animPos = { x = 291.78, y = -1078.61, z = 29.4, h = 91.55},   -- The animation position
    },
	
	["integrity-way"] = {
        pos = { x = -46.96, y = -584.67, z = 37.95, h = 249.16},  -- door coords
        locked = true,
        cooldown = 0,
        inside = { x = -24.37, y = -597.68, z = 80.03, h = 237.79},  -- Inside coords
        animPos = { x = -46.96, y = -584.67, z = 37.95, h = 249.16},   -- The animation position
    },
}

Config.burglaryInside = {
    --Tinsel Towers Apt 42--- $2450ish max (very unlikely) 1/24 chance per search
	["draw1"] = { x = -601.45, y = 45.85, z = 97.40, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw2"] = { x = -601.45, y = 43.62, z = 97.40, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["speaker1"] = { x = -604.26, y = 40.90, z = 97.40, items = {'speaker', 'junk', 'speaker','junk','junk'}, names = {'Speaker', 'Junk', 'Speaker','Junk'}, amount = math.random(1,2)},
	["speaker2"] = { x = -608.47, y = 40.79, z = 97.40, items = {'speaker', 'junk', 'speaker','junk','junk'}, names = {'Speaker', 'Junk', 'Speaker','Junk'}, amount = math.random(1,2)},
	--bedroom
	["draw3"] = { x = -598.58, y = 49.69, z = 97.03, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw4"] = { x = -598.58, y = 47.81, z = 97.11, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw5"] = { x = -593.20, y = 50.45, z = 96.50, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["draw6"] = { x = -597.42, y = 52.15, z = 97.00, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw7"] = { x = -593.20, y = 47.00, z = 96.50, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["wardrobe1"] = { x = -595.95, y = 56.13, z = 97.0, items = {'junk','ring','junk','omega','junk'}, names = {'Junk', 'Gold Ring','Junk','Omega Watch','Junk'}, amount = math.random(1,1)},
	["wardrobe2"] = { x = -593.22, y = 56.13, z = 97.0, items = {'junk','ring','junk','oldcoin','junk'}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk'}, amount = math.random(1,1)},
	--office
	["laptoptable1"] = { x = -625.50, y = 50.14, z = 97.50, items = {'laptop','junk','gamingperipherals'}, names = {'Laptop','Junk','Headphones'}, amount = math.random(1,1)},
	--bathroom
	["sinkl"] = { x = -589.89, y = 52.70, z = 97.00, items = {'junk','dildo','junk','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, amount = math.random(1,1)},
	["sink2"] = { x = -590.03, y = 50.05, z = 96.50, items = {'junk','dildo','junk','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, amount = math.random(1,1)},
	 
	 
	--apt-hill-crest1 ---- $2050ish max (very unlikely) 1/24 chance per search
	["draw8"] = { x = -672.68, y = 581.6, z = 144.97, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw9"] = { x = -674.76, y = 584.88, z = 145.00, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["skybox1"] = { x = -664.40, y = 585.27, z = 144.30, items = {'console','console','junk','junk'}, names = {'PS4','Xbox 1','Junk','Junk'}, amount = math.random(1,1)},
	 --kitchen
	["draw10"] = { x = -675.73, y = 595.65, z = 145.38, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["draw11"] = { x = -674.09, y = 593.43, z = 145.38, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw12"] = { x = -673.00, y = 595.06, z = 145.38, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	--bedroom
	["speaker3"] = { x = -672.00, y = 581.21, z = 141.57, items = {'speaker', 'junk', 'speaker','junk','ifruit'}, names = {'Speaker','Junk','Speaker','Junk','ifruit'}, amount = math.random(1,1)},
	["draw13"] = { x = -664.45, y = 584.89, z = 141.40, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["wardrobe3"] = { x = -672.00, y = 587.6, z = 141.57, items = {'junk','ring','junk','oldcoin','junk','rolex'}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk','Rolex Watch'}, amount = math.random(1,1)},
	--bathroom
	["18ct Diamond Ring"] = { x = -674.27, y = 595.29, z = 141.50, items = {'junk','dildo','junk','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, amount = math.random(1,1)},
	["Hairspray"] = { x = -673.40, y = 595.80, z = 141.50, items = {'junk','dildo','junk','ring'}, names = {'Strap On','Dildo','Book','Gold Ring'}, amount = math.random(1,1)},
	--downstairs
	["shelve1"] = { x = -682.05, y = 596.33, z = 137.88, items = {'junk','ring','junk','oldcoin','junk'}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk'}, amount = math.random(1,1)},
	
	
	--apt-hill-crest2 ---- $2450ish max (very unlikely) 1/24 chance per search
	["draw14"] = { x = -768.24, y = 615.00, z = 143.33, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["draw15"] = { x = -758.26, y = 611.59, z = 144.00, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["shelve2"] = { x = -768.05, y = 608.07, z = 143.93, items = {'junk','ring','junk','passport','junk'}, names = {'Junk', 'Ring','Junk','Passport','Junk'}, amount = math.random(1,2)},
	["Treasure Map"] = { x = -773.13, y = 613.82, z = 143.73, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifuit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Sojo Beans"] = { x = -759.46, y = 609.63, z = 144.14, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifuit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw16"] = { x = -761.59, y = 613.22, z = 144.14, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifuit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	--bedroom
	["drawadded"] = { x = -774.54, y = 613.14, z = 140.70, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["drawadded2"] = { x = -772.95, y = 613.60, z = 140.40, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["drawadded3"] = { x = -772.13, y = 605.28, z = 140.25, items = {'laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["drawadded4"] = { x = -769.31, y = 606.24, z = 140.25, items = {'laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["sinkadded"] = { x = -759.14, y = 610.45, z = 140.00, items = {'junk','dildo','junk','ring','oldcoin'}, names = {'Junk','Dildo','Book','Gold Ring','Old Coin'}, amount = math.random(1,2)},
	--downstairs
	["Book of Ree"] = { x = -755.02, y = 617.38, z = 136.88, items = {'junk','ring','junk','oldcoin','junk','junk'}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk','Junk'}, amount = math.random(1,2)},
	["Cracked Ornament"] = { x = -760.85, y = 619.01, z = 136.52, items = {'junk','rareornament','junk','oldcoin','junk'}, names = {'Junk', 'Rare Ornament','Junk','Old Coin','Junk'}, amount = math.random(1,1)},
	["laptoptable2"] = { x = -763.41, y = 613.43, z = 136.53, items = {'laptop','junk','gamingperipherals','junk'}, names = {'Laptop','Junk','Mouse','Junk'}, amount = math.random(1,1)},
	["laptoptable3"] = { x = -760.74, y = 614.33, z = 136.53, items = {'tablet','junk','junk','junk'}, names = {'ipad','Junk','Junk','Junk'}, amount = math.random(1,1)},
	
	
	--apt-hill-crest3 ---- $2450ish max (very unlikely) 1/24 chance per search
	["draw15"] = { x = -859.50, y = 675.05, z = 152.45, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw18"] = { x = -856.12, y = 686.08, z = 152.88, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw17"] = { x = -852.16, y = 687.18, z = 152.88, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["drawadded6"] = { x = -853.79, y = 688.90, z = 152.65, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["drawadded5"] = { x = -859.72, y = 679.15, z = 152.65, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["skybox2"] = { x = -851.18, y = 674.83, z = 152.45, items = {'console','console','junk','junk'}, names = {'PS4','Xbox 1','Junk','Junk'}, amount = math.random(1,1)},
	--downstairs
	["Panther Ornament"] = { x = -860.95, y = 693.26, z = 149.45, items = {'rareornament','junk','junk','oldcoin'}, names = {'rareornament','junk','junk','Old Coin'}, amount = math.random(1,1)},
	["Breath Fresh"] = { x = -853.52, y = 687.72, z = 149.07, items = {'junk','diamond','junk','ring','diamondring'}, names = {'Strap On','Diamond','Book','Gold Ring','Diamond Ring'}, amount = math.random(1,1)},
	["9ct Ring"] = { x = -852.08, y = 687.72, z = 149.07, items = {'junk','dildo','junk','ring','diamondring'}, names = {'Strap On','Dildo','Book','Gold Ring','Diamond Ring'}, amount = math.random(1,1)},
	["shelve3"] = { x = -854.72, y = 680.32, z = 149.05, items = {'junk','ring','junk','omega','junk','rolex','junk'}, names = {'Junk', 'Gold Ring','Junk','Omega Watch','Junk','Rolex Watch','Junk'}, amount = math.random(1,1)},
	["Pot Ornament"] = { x = -859.2, y = 695.81, z = 145.24, items = {'junk','rareornament','junk','oldcoin','junk'}, names = {'Junk', 'Rare Ornament','Junk','Old Coin','Junk'}, amount = math.random(1,1)},
	["draw19"] = { x = -856.1, y = 699.15, z = 145.25, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["wardrobe4"] = { x = -859.53, y = 675.24, z = 148.85, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["Broken Watch"] = { x = -851.13, y = 677.22, z = 148.85, items = {'junk','dildo','junk','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, amount = math.random(1,1)},
	
	--corkers-ave -  (near pawnshop)--- $1600ish max (very unlikely) 1/24 chance per search
	["draw20"] = { x = 368.80, y = 408.21, z = 145.5, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["draw21"] = { x = 368.80, y = 407.68, z = 145.5, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Book of Memes"] = { x = 373.31 , y = 426.03, z = 143.10, items = {'junk','dildo','junk','ring','goldbracelet'}, names = {'Junk','Dildo','Book','Gold Ring','Gold Bracelet'}, amount = math.random(1,1)},
	["Bowl"] = { x = 377.75, y = 419.67, z = 145.9, items = {'junk','ring','junk','oldcoin','junk'}, names = {'Junk', 'Gold Ring','Junk','Old Coin','Junk'}, amount = math.random(1,1)},
	--downstairs
	["SteelSeries Headphones"] = { x = 373.35, y = 433.39, z = 138.30, items = {'laptop','junk','gamingperipherals','junk'}, names = {'Laptop','Junk','Keyboard','Junk'}, amount = math.random(1,1)},
	--bedroom
	["Pink Thing"] = { x = 376.69, y = 404.06, z = 141.75, items = {'junk','dildo','junk','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, amount = math.random(1,1)},
	["Amber Leaf"] = { x = 373.62, y = 412.50, z = 142.10, items = {'junk','junk','lotteryticket'}, names = {'junk','Junk','Lottery Ticket'}, amount = math.random(1,2)},
	["Lotto2"] = { x = 368.61, y = 406.54, z = 142.10, items = {'wallet','pickledanimal','junk'}, names = {'Wallet','Zevas Jar of Pickled Animals','junk'}, amount = math.random(1,1)},
	["Zevas"] = { x = 369.11, y = 403.36, z = 141.50, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Diamond"] = { x = 377.57, y = 419.12, z = 141.40, items = {'diamond','junk','junk'}, names = {'Diamond','junk','junk'}, amount = math.random(1,1)},
	["added"] = { x = 379.36, y = 429.82, z = 138.3, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	
	
	
	--apt-de-base(nesr PD) -- high risk, higher reward $2450ish max (very unlikely) 1/24 chance per search
	--bed
	["Rolex"] = { x = 262.95, y = -1004.51, z = -98.90, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	--main room
	["Leather Wallet"] = { x = 266.10, y = -999.4, z = -99.01, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Fake Passport"] = { x = 260.19, y = -997.11, z = -97.30, items = {'omega','rolex','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Mouldy Spoon"] = { x = 266.11, y = -996.59, z = -99.01, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["18ct Ring"] = { x = 256.90, y = -1001.49, z = -99.01, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["FHM"] = { x = 260.80, y = -994.87, z = -99.50, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Packet of RAWS"] = { x = 262.53, y = -1000.27, z = -99.30, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["Picture Frame"] = { x = 256.25, y = -996.95, z = -98.41, items = {'junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Ripped Clothes"] = { x = 260.68, y = -1004.6, z = -99.01, items = {'laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Xbox One"] = { x = 263.03, y = -1002.47, z = -99.00, items = {'console','console','junk','junk'}, names = {'PS4','Xbox 1','Junk','Junk'}, amount = math.random(1,1)},
	
	--integirty-way - $2050ish max (very unlikely) 1/25 chance per search---
	["speakeradded2"] = { x = -604.26, y = 40.90, z = 97.40, items = {'speaker', 'junk', 'speaker','junk','junk'}, names = {'Speaker', 'Junk', 'Speaker','Junk'}, amount = math.random(1,2)},
	["speakeradded"] = { x = -604.26, y = 40.90, z = 97.40, items = {'speaker', 'junk', 'speaker','junk','junk'}, names = {'Speaker', 'Junk', 'Speaker','Junk'}, amount = math.random(1,2)},
	--bedroom
	["9c Ringg"] = { x = -27.32, y = -580.18, z = 79.23, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Packet of Tissues"] = { x = -11.81, y = -599.34, z = 79.43, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["drawaddedx"] = { x = -34.36, y = -586.70, z = 78.83, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	["drawaddedy"] = { x = -37.31, y = -583.69, z = 78.50, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["drawaddedp"] = { x = -36.23, y = -580.71 , z = 78.50, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,2)},
	--printer
	["Rolex Submariner"] = { x = -9.34, y = -599.51, z = 79.43, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	--bathroom
	["Showercap"] = { x = -40.57, y = -582.22, z = 78.0, items = {'junk','dildo','junk','ring'}, names = {'Junk','Dildo','Book','Gold Ring'}, amount = math.random(1,1)},
	["22ct Diamond Ring"] = { x = -41.40, y = -584.80, z = 78.65, items = {'junk','dildo','junk','ring','diamondring'}, names = {'Junk','Dildo','Book','Gold Ring','diamondring'}, amount = math.random(1,1)},
	["Remote"] = { x = -31.76, y = -583.29, z = 78.87, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["PS4"] = { x = -22.69, y = -579.47, z = 78.80, items = {'console','console','junk','junk'}, names = {'PS4','Xbox 1','Junk','Junk'}, amount = math.random(1,1)},
	["drawt"] = { x = -10.50, y = -584.59, z = 79.6, items = {'omega','rolex','laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Omega Watch', 'Rolex Watch','Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["drawy"] = { x = -13.01, y = -589.67, z = 79.43, items = {'laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
	["Folder "] = { x = -7.20, y = -594.15, z = 79.43, items = {'laptop','junk','junk','pickledanimal','santashat','ifruit','wallet','gpspill','sojobeans','diamondring','goldchain','creditcard','ring','oldcoin','passport','rarecoin','diamond','tablet','goldbracelet','treasuremap','dildo','lotteryticket'}, names = {'Laptop','Junk','Junk','Zevas Jar of Pickled Animals','Santas Hat','ifruit','Wallet','GPS Pill','Sojo Beans','Diamond Ring','Gold Chain','Credit Card','Ring','Old Coin','Passport','Rare Coin','Diamond','Tablet','Gold Bracelet','Treasure Map','Dildo','Lottery Ticket'}, amount = math.random(1,1)},
}

Config.closets = {
    ["Robban's Closet"] = { x = 351.24, y = -993.53, z = -99.2, items = {'shirt', 'pants', 'hat', 'shoes'}, shirtAmount = math.random(1,3), pantsAmount = math.random(1,3), hatAmount = math.random(1,2), shoesAmount = math.random(1,2)},
}
